<a href="https://colab.research.google.com/github/GabrielYYM/Notebooks/blob/main/UsingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array_zero = np.zeros ((3, 3))
array_rand = np.random.rand(3)
print (array_rand)
print (array_zero)

[0.87836589 0.68448346 0.11638662]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
array1 = np.array([[1, 2, 3], [1, 2, 3]])
array2 = np.array([[7, 6, 4], [4, 5, 6]])

produto = np.prod(array1) * np.prod(array2)
print(produto)



725760


In [ ]:
numero1 = 50

log = np.log(numero1)
print(log)

3.912023005428146
